sudo:     true
language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

install:  "pip install -r requirements.txt"
script:   pytest

# TODO
# after_success:
#   - pip install coveralls
#   - coveralls
